version: '2'
services:
  syncthing:
    image: istepanov/syncthing
    container_name: syncthing
    restart: always
    networks:
      - front
    expose:
      - "8384"
    ports:
      - "22000:22000"
      - "21025:21025/udp"
    volumes:
      - config:/home/syncthing/.config/syncthing
      - data:/home/syncthing/Sync
    environment:
      - VIRTUAL_HOST=${SYNCTHING_VIRTUAL_HOST}
      - VIRTUAL_PORT=8384
      - LETSENCRYPT_HOST=${SYNCTHING_VIRTUAL_HOST}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}

volumes:
  data:
  config:

networks:
  front:
    external:
      name: proxy_front